// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptIncomingFile(arg1) {
  return window['go']['main']['App']['AcceptIncomingFile'](arg1);
}

export function CheckPermissions() {
  return window['go']['main']['App']['CheckPermissions']();
}

export function ClearAllTrustedDevices() {
  return window['go']['main']['App']['ClearAllTrustedDevices']();
}

export function CreateVirtualDisplay(arg1) {
  return window['go']['main']['App']['CreateVirtualDisplay'](arg1);
}

export function DestroyVirtualDisplay() {
  return window['go']['main']['App']['DestroyVirtualDisplay']();
}

export function DownloadADB() {
  return window['go']['main']['App']['DownloadADB']();
}

export function ExtendDisplay(arg1) {
  return window['go']['main']['App']['ExtendDisplay'](arg1);
}

export function ForgetTrustedDevice(arg1) {
  return window['go']['main']['App']['ForgetTrustedDevice'](arg1);
}

export function GetActiveTransfers() {
  return window['go']['main']['App']['GetActiveTransfers']();
}

export function GetAutoDiscovery() {
  return window['go']['main']['App']['GetAutoDiscovery']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConnectedClients() {
  return window['go']['main']['App']['GetConnectedClients']();
}

export function GetMenuBarVisible() {
  return window['go']['main']['App']['GetMenuBarVisible']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetStreamStatus() {
  return window['go']['main']['App']['GetStreamStatus']();
}

export function GetUSBAutoAccept() {
  return window['go']['main']['App']['GetUSBAutoAccept']();
}

export function GetUSBStatus() {
  return window['go']['main']['App']['GetUSBStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasAccessibility(arg1) {
  return window['go']['main']['App']['HasAccessibility'](arg1);
}

export function IsMirrored(arg1) {
  return window['go']['main']['App']['IsMirrored'](arg1);
}

export function ListDisplays() {
  return window['go']['main']['App']['ListDisplays']();
}

export function ListTrustedDevices() {
  return window['go']['main']['App']['ListTrustedDevices']();
}

export function MirrorDisplay(arg1, arg2) {
  return window['go']['main']['App']['MirrorDisplay'](arg1, arg2);
}

export function OnClientConnect(arg1, arg2) {
  return window['go']['main']['App']['OnClientConnect'](arg1, arg2);
}

export function OnClientDisconnect(arg1) {
  return window['go']['main']['App']['OnClientDisconnect'](arg1);
}

export function OnClientDownloadAccept(arg1, arg2) {
  return window['go']['main']['App']['OnClientDownloadAccept'](arg1, arg2);
}

export function OnClientDownloadComplete(arg1, arg2) {
  return window['go']['main']['App']['OnClientDownloadComplete'](arg1, arg2);
}

export function OnClientDownloadReject(arg1, arg2) {
  return window['go']['main']['App']['OnClientDownloadReject'](arg1, arg2);
}

export function OnClientFileAccept(arg1, arg2) {
  return window['go']['main']['App']['OnClientFileAccept'](arg1, arg2);
}

export function OnClientFileChunk(arg1, arg2) {
  return window['go']['main']['App']['OnClientFileChunk'](arg1, arg2);
}

export function OnClientFileComplete(arg1, arg2) {
  return window['go']['main']['App']['OnClientFileComplete'](arg1, arg2);
}

export function OnClientFileOffer(arg1, arg2) {
  return window['go']['main']['App']['OnClientFileOffer'](arg1, arg2);
}

export function OnClientFileReject(arg1, arg2) {
  return window['go']['main']['App']['OnClientFileReject'](arg1, arg2);
}

export function OnClientInput(arg1, arg2) {
  return window['go']['main']['App']['OnClientInput'](arg1, arg2);
}

export function OnClientResize(arg1, arg2) {
  return window['go']['main']['App']['OnClientResize'](arg1, arg2);
}

export function PickAndSendFile() {
  return window['go']['main']['App']['PickAndSendFile']();
}

export function RejectIncomingFile(arg1) {
  return window['go']['main']['App']['RejectIncomingFile'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function SendFile(arg1) {
  return window['go']['main']['App']['SendFile'](arg1);
}

export function SendFileToPhone(arg1) {
  return window['go']['main']['App']['SendFileToPhone'](arg1);
}

export function ServeDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['ServeDownload'](arg1, arg2, arg3);
}

export function SetAutoDiscovery(arg1) {
  return window['go']['main']['App']['SetAutoDiscovery'](arg1);
}

export function SetMenuBarVisible(arg1) {
  return window['go']['main']['App']['SetMenuBarVisible'](arg1);
}

export function SetPairCode(arg1) {
  return window['go']['main']['App']['SetPairCode'](arg1);
}

export function SetUSBAutoAccept(arg1) {
  return window['go']['main']['App']['SetUSBAutoAccept'](arg1);
}

export function SetupUSB() {
  return window['go']['main']['App']['SetupUSB']();
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StartStream(arg1) {
  return window['go']['main']['App']['StartStream'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function StopStream() {
  return window['go']['main']['App']['StopStream']();
}

export function TakeSnapshot(arg1) {
  return window['go']['main']['App']['TakeSnapshot'](arg1);
}

export function TeardownUSB() {
  return window['go']['main']['App']['TeardownUSB']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
