// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {adb} from '../models';
import {protocol} from '../models';

export function AcceptIncomingFile(arg1:string):Promise<void>;

export function CheckPermissions():Promise<void>;

export function CreateVirtualDisplay(arg1:main.VirtualDisplayConfig):Promise<number>;

export function DestroyVirtualDisplay():Promise<void>;

export function DownloadADB():Promise<void>;

export function ExtendDisplay(arg1:number):Promise<void>;

export function GetActiveTransfers():Promise<Array<Record<string, any>>>;

export function GetConfig():Promise<main.AppConfig>;

export function GetConnectedClients():Promise<Array<main.ClientInfo>>;

export function GetMenuBarVisible():Promise<boolean>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function GetStreamStatus():Promise<main.StreamStatus>;

export function GetUSBStatus():Promise<adb.Status>;

export function GetVersion():Promise<string>;

export function HasAccessibility(arg1:boolean):Promise<boolean>;

export function IsMirrored(arg1:number):Promise<boolean>;

export function ListDisplays():Promise<Array<main.DisplayInfo>>;

export function MirrorDisplay(arg1:number,arg2:number):Promise<void>;

export function OnClientConnect(arg1:protocol.Session,arg2:protocol.HelloMessage):Promise<void>;

export function OnClientDisconnect(arg1:protocol.Session):Promise<void>;

export function OnClientFileAccept(arg1:protocol.Session,arg2:protocol.FileAcceptMessage):Promise<void>;

export function OnClientFileChunk(arg1:protocol.Session,arg2:protocol.FileChunkMessage):Promise<void>;

export function OnClientFileComplete(arg1:protocol.Session,arg2:protocol.FileCompleteMessage):Promise<void>;

export function OnClientFileOffer(arg1:protocol.Session,arg2:protocol.FileOfferMessage):Promise<void>;

export function OnClientFileReject(arg1:protocol.Session,arg2:protocol.FileRejectMessage):Promise<void>;

export function OnClientInput(arg1:protocol.Session,arg2:protocol.InputMessage):Promise<void>;

export function OnClientResize(arg1:protocol.Session,arg2:protocol.ResizeMessage):Promise<void>;

export function PickAndSendFile():Promise<void>;

export function RejectIncomingFile(arg1:string):Promise<void>;

export function ResetConfig():Promise<void>;

export function SendFile(arg1:string):Promise<void>;

export function SetMenuBarVisible(arg1:boolean):Promise<void>;

export function SetupUSB():Promise<void>;

export function StartServer():Promise<void>;

export function StartStream(arg1:main.StreamConfig):Promise<void>;

export function StopServer():Promise<void>;

export function StopStream():Promise<void>;

export function TakeSnapshot(arg1:number):Promise<Array<number>>;

export function TeardownUSB():Promise<void>;

export function UpdateConfig(arg1:main.AppConfig):Promise<void>;
